### ISSUE TITLE
FTP upload file fails

### ISSUE THREAD

**Issue by Mcpoowl** [Mcpoowl/SFTPModule#4]
Uploading a file using the regular FTP option fails.

See: https://mxforum.mendix.com/questions/8373/FTP-Module--Fail-to-upload-document

**Comment by SolvosNSA** [comment]
Is there a way I can contact you privately (new to github). I can provide you the settings but I'd rather not put them in the open. Settings I used are

FTP Type: FTP
Hostname fpt.company.nl
Port 21
Username
Password
Passphrase: none
Home folder: /solvos ftp
Keep remote file: true/false (tried both)
Use user credentials: false

**Comment by Mcpoowl** [comment]
@SolvosNSA You can write me an email at paul dot ketelaars at pinkelephant dot nl

**Comment by Mcpoowl** [comment]
Problem was not in the module, but in the configuration. Issue closed.
